# Server Configuration
server.port=8080

# AWS Configuration
spring.application.name=app
aws.region=us-east-1
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always

# DynamoDB Table Names
dynamodb.table.products=Products
dynamodb.table.orders=Orders

# CORS Configuration
spring.mvc.cors.allowed-origins=http://localhost:5173
spring.mvc.cors.allowed-methods=GET,POST,PUT,DELETE
spring.mvc.cors.allowed-headers=*

# Email Configuration (will be configured via environment variables in ECS)
aws.ses.fromEmail=rajasabarish18@gmail.com


# Logging Configuration
logging.level.com.appointment.app=DEBUG
logging.level.software.amazon.awssdk=INFO

product.image.laptop=https://media-ik.croma.com/prod/https://media.croma.com/image/upload/v1739458788/Croma%20Assets/Computers%20Peripherals/Laptop/Images/305609_0_tqf4sy.png?tr=w-600
product.image.smartphone=https://m.media-amazon.com/images/I/71lD7eGdW-L._AC_UF1000,1000_QL80_.jpg
product.image.headphones=https://thumbs.dreamstime.com/b/samsung-galaxy-buds-pro-lviv-ukraine-april-339360726.jpg
product.image.tablet=https://media.istockphoto.com/id/2152881332/photo/tablet-samsung-sm-t725n-galaxy-tab-s5e-10-5-lte-black.jpg?s=612x612&w=0&k=20&c=x4GfY1jpIu8Bwvh5yTdRVD8cWT5OJoE5lANTdyyniR8=

